import type { ReactNode } from 'react';
import type { Language } from './types';

export interface Translation {
  appTitle: string;
  appDescription: string;
  stepsIntro: string;
  step1: ReactNode;
  step2: ReactNode;
  step3: ReactNode;
  placeholder: string;
  generateButton: string;
  divergenceTitle: string;
  exploreAlternative: string;
  realTimeline: string;
  alternativeTimeline: string;
  imageError: string;
  baseEventError: string;
  alternativeGenerationError: string;
  unknownError: string;
  loading: string;
  imageAlt: (title: string) => string;
  imageProgress: (current: number, total: number) => string;
  switchToEnglish: string;
  switchToSpanish: string;
}

export const translations: Record<Language, Translation> = {
  es: {
    appTitle: 'Cronista Contrafactual',
    appDescription: 'Explora líneas de tiempo históricas y alternativas generadas por IA.',
    stepsIntro: 'Sigue estos pasos:',
    step1: (
      <>
        <strong>Escribe</strong> el nombre de un personaje histórico. Para la demo puedes comenzar con <em>Blas de Lezo</em>.
      </>
    ),
    step2: (
      <>
        <strong>Genera</strong> su línea temporal real basada en información histórica curada.
      </>
    ),
    step3: (
      <>
        <strong>Explora</strong> puntos de divergencia y crea líneas alternativas con imágenes del modelo <em>Nano Banana</em> de Google Gemini.
      </>
    ),
    placeholder: 'Escribe un personaje histórico',
    generateButton: 'Generar Línea Temporal',
    divergenceTitle: 'Punto de Divergencia',
    exploreAlternative: 'Explorar línea temporal alternativa',
    realTimeline: 'Línea Temporal Real',
    alternativeTimeline: 'Línea Temporal Alternativa',
    imageError: 'Error al generar imagen',
    baseEventError: 'No se pudo encontrar el evento base o su imagen para la divergencia.',
    alternativeGenerationError: 'No se pudo generar la línea temporal alternativa.',
    unknownError: 'Ocurrió un error desconocido.',
    loading: 'Cargando...',
    imageAlt: (title: string) => `Imagen del evento: ${title}`,
    imageProgress: (current, total) => `Imágenes generadas: ${current} de ${total}`,
    switchToEnglish: 'Cambiar a inglés',
    switchToSpanish: 'Cambiar a español',
  },
  en: {
    appTitle: 'Counterfactual Chronicler',
    appDescription: 'Explore historical and alternative timelines generated by AI.',
    stepsIntro: 'Follow these steps:',
    step1: (
      <>
        <strong>Enter</strong> the name of an historical figure. For the demo you can start with <em>Blas de Lezo</em>.
      </>
    ),
    step2: (
      <>
        <strong>Generate</strong> their real timeline based on curated historical information.
      </>
    ),
    step3: (
      <>
        <strong>Explore</strong> divergence points and create alternative timelines with images from Google Gemini's <em>Nano Banana</em> model.
      </>
    ),
    placeholder: 'Enter an historical figure',
    generateButton: 'Generate Timeline',
    divergenceTitle: 'Divergence Point',
    exploreAlternative: 'Explore alternative timeline',
    realTimeline: 'Real Timeline',
    alternativeTimeline: 'Alternative Timeline',
    imageError: 'Image generation failed',
    baseEventError: 'Could not find the base event or its image for the divergence.',
    alternativeGenerationError: 'Failed to generate the alternative timeline.',
    unknownError: 'An unknown error occurred.',
    loading: 'Loading...',
    imageAlt: (title: string) => `Image of event: ${title}`,
    imageProgress: (current, total) => `Images generated: ${current} of ${total}`,
    switchToEnglish: 'Switch to English',
    switchToSpanish: 'Switch to Spanish',
  },
};
